import * as pdfjsLib from "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs";
pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs";

const $=id=>document.getElementById(id);
const state={pdf:null,file:null,original:null,page:1,scale:1,tool:"select",color:"#ffe34d",size:4,annotations:{},strokes:[],highlights:[],notes:[]};
let renderTask=null,drawing=false,currentStroke=null,start=null,preview=null;

const setStatus=s=>$("saveStatus").textContent=s;
const error=s=>$("errorBox").textContent=s||"";
const pageData=()=>state.annotations[state.page]||(state.annotations[state.page]={strokes:[],highlights:[],notes:[]});
function syncPage(){const d=pageData();state.strokes=d.strokes;state.highlights=d.highlights;state.notes=d.notes}
function savePage(){state.annotations[state.page]={strokes:state.strokes,highlights:state.highlights,notes:state.notes};setStatus("Changes saved locally")}
function enable(on){["prevPage","nextPage","pageNumber","zoomOut","zoomIn","fitPage","addNote","downloadPdf","downloadAnnotations","clearPage"].forEach(id=>$(id).disabled=!on)}
function nav(){ $("pageNumber").value=state.page;$("pageCount").textContent=state.pdf?.numPages||"—";$("prevPage").disabled=!state.pdf||state.page<=1;$("nextPage").disabled=!state.pdf||state.page>=state.pdf.numPages;$("zoomLabel").textContent=Math.round(state.scale*100)+"%" }
function tool(t){state.tool=t;document.querySelectorAll("[data-tool]").forEach(b=>b.classList.toggle("active",b.dataset.tool===t));$("toolHint").textContent={select:"Select and navigate the PDF.",highlight:"Drag a rectangle over the page to highlight.",pen:"Draw directly on the page.",eraser:"Draw over strokes to erase them.",note:"Click the page to place the note from the text box."}[t]}
function color(c){state.color=c;document.querySelectorAll(".color").forEach(b=>b.classList.toggle("active",b.dataset.color===c))}
function pos(e){const r=$("inkCanvas").getBoundingClientRect();return[Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))]}
function renderHighlights(){const layer=$("highlightLayer");layer.innerHTML="";for(const h of state.highlights){const el=document.createElement("div");el.className="hl";Object.assign(el.style,{left:h.x*100+"%",top:h.y*100+"%",width:h.w*100+"%",height:h.h*100+"%",background:h.color+"99"});layer.append(el)}}
function renderStrokes(){const c=$("inkCanvas"),ctx=c.getContext("2d");ctx.clearRect(0,0,c.width,c.height);ctx.lineCap="round";ctx.lineJoin="round";for(const s of state.strokes){if(!s.points.length)continue;ctx.strokeStyle=s.color;ctx.lineWidth=s.size*state.scale;ctx.beginPath();ctx.moveTo(s.points[0][0]*c.width,s.points[0][1]*c.height);for(let i=1;i<s.points.length;i++)ctx.lineTo(s.points[i][0]*c.width,s.points[i][1]*c.height);ctx.stroke()}}
function renderNotes(){const layer=$("noteLayer");layer.innerHTML="";state.notes.forEach(n=>{const b=document.createElement("button");b.className="note-pin";b.textContent="N";b.title=n.text;b.style.left=n.x*100+"%";b.style.top=n.y*100+"%";b.onclick=()=>{$("noteText").value=n.text;$("noteText").focus()};layer.append(b)});const list=$("notesList");list.innerHTML="";if(!state.notes.length){list.innerHTML='<p class="muted">No notes on this page.</p>';return}state.notes.forEach((n,i)=>{const d=document.createElement("div");d.className="note-item";d.innerHTML=`<small>Page ${state.page}</small><div></div><button>Delete</button>`;d.querySelector("div").textContent=n.text;d.querySelector("button").onclick=()=>{state.notes.splice(i,1);savePage();renderNotes()};list.append(d)})}
function overlays(){renderHighlights();renderStrokes();renderNotes()}
async function renderPage(){if(!state.pdf)return;syncPage();if(renderTask)try{renderTask.cancel()}catch{}const p=await state.pdf.getPage(state.page);const v=p.getViewport({scale:state.scale});$("pageStage").style.width=v.width+"px";$("pageStage").style.height=v.height+"px";$("pdfCanvas").width=v.width;$("pdfCanvas").height=v.height;$("inkCanvas").width=v.width;$("inkCanvas").height=v.height;renderTask=p.render({canvasContext:$("pdfCanvas").getContext("2d"),viewport:v});try{await renderTask.promise}catch(e){if(e.name!=="RenderingCancelledException")error(e.message)}overlays();nav()}
async function openFile(file){if(!file)return;if(file.type!=="application/pdf"&&!file.name.toLowerCase().endsWith(".pdf"))return error("Please choose a PDF file.");try{setStatus("Opening PDF…");const buf=await file.arrayBuffer();state.pdf=await pdfjsLib.getDocument({data:new Uint8Array(buf)}).promise;state.file=file;state.original=new Uint8Array(buf);state.page=1;state.scale=1;state.annotations={};$("fileName").textContent=file.name;$("fileMeta").textContent=Math.round(file.size/1024)+" KB · "+state.pdf.numPages+" pages";$("emptyState").hidden=true;$("viewerContent").hidden=false;enable(true);await renderPage();setStatus("PDF ready")}catch(e){error("Could not open PDF: "+e.message);setStatus("Error")}}
function hit(p,s){return s.points.some(q=>Math.hypot((q[0]-p[0])*$("inkCanvas").width,(q[1]-p[1])*$("inkCanvas").height)<Math.max(12,s.size*state.scale+8))}
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>tool(b.dataset.tool));
document.querySelectorAll(".color").forEach(b=>b.onclick=()=>color(b.dataset.color));
$("penSize").onchange=e=>state.size=Number(e.target.value);
$("uploadTop").onclick=$("emptyUpload").onclick=()=>$("fileInput").click();
$("fileInput").onchange=e=>openFile(e.target.files[0]);
$("prevPage").onclick=()=>{if(state.page>1){savePage();state.page--;renderPage()}};
$("nextPage").onclick=()=>{if(state.page<state.pdf.numPages){savePage();state.page++;renderPage()}};
$("pageNumber").onchange=e=>{savePage();state.page=Math.max(1,Math.min(state.pdf.numPages,Number(e.target.value)||1));renderPage()};
$("zoomIn").onclick=()=>{state.scale=Math.min(4,state.scale+.25);renderPage()};
$("zoomOut").onclick=()=>{state.scale=Math.max(.25,state.scale-.25);renderPage()};
$("fitPage").onclick=()=>{state.scale=Math.max(.2,Math.min(3,($("paperArea").clientWidth-16)/($("pageStage").offsetWidth/state.scale)));renderPage()};
$("inkCanvas").addEventListener("pointerdown",e=>{if(!state.pdf)return;if(state.tool==="pen"||state.tool==="eraser"){drawing=true;currentStroke={points:[pos(e)],color:state.color,size:state.size};$("inkCanvas").setPointerCapture(e.pointerId)}else if(state.tool==="highlight")start=pos(e)});
$("inkCanvas").addEventListener("pointermove",e=>{if(state.tool==="highlight"&&start){const p=pos(e),x=Math.min(start[0],p[0]),y=Math.min(start[1],p[1]),w=Math.abs(p[0]-start[0]),h=Math.abs(p[1]-start[1]);if(!preview){preview=document.createElement("div");preview.className="hl";$("highlightLayer").append(preview)}Object.assign(preview.style,{left:x*100+"%",top:y*100+"%",width:w*100+"%",height:h*100+"%",background:state.color+"99"})}if(!drawing||!currentStroke)return;const p=pos(e);if(state.tool==="pen"){currentStroke.points.push(p);renderStrokes();const c=$("inkCanvas"),ctx=c.getContext("2d"),a=currentStroke.points,prev=a[a.length-2];ctx.strokeStyle=currentStroke.color;ctx.lineWidth=currentStroke.size*state.scale;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(prev[0]*c.width,prev[1]*c.height);ctx.lineTo(p[0]*c.width,p[1]*c.height);ctx.stroke()}else{state.strokes=state.strokes.filter(s=>!hit(p,s));renderStrokes()}});
$("inkCanvas").addEventListener("pointerup",e=>{if(state.tool==="pen"&&drawing&&currentStroke){state.strokes.push(currentStroke);savePage()}if(state.tool==="highlight"&&start){const p=pos(e),x=Math.min(start[0],p[0]),y=Math.min(start[1],p[1]),w=Math.abs(p[0]-start[0]),h=Math.abs(p[1]-start[1]);if(w>.005&&h>.005){state.highlights.push({x,y,w,h,color:state.color});savePage()}if(preview){preview.remove();preview=null}renderHighlights()}drawing=false;currentStroke=null;start=null});
$("inkCanvas").addEventListener("click",e=>{if(state.tool==="note"){const text=$("noteText").value.trim();if(text){const p=pos(e);state.notes.push({x:p[0],y:p[1],text});savePage();renderNotes();$("noteText").value=""}}});
$("addNote").onclick=()=>{const text=$("noteText").value.trim();if(!text||!state.pdf)return;state.notes.push({x:.8,y:.15,text});savePage();renderNotes();$("noteText").value=""};
$("clearPage").onclick=()=>{if(confirm("Clear all annotations on this page?")){state.strokes=[];state.highlights=[];state.notes=[];savePage();overlays()}};
$("downloadPdf").onclick=()=>{if(state.original)download(new Blob([state.original],{type:"application/pdf"}),(state.file?.name||"document.pdf").replace(/\.pdf$/i,"")+"-original.pdf")};
$("downloadAnnotations").onclick=()=>{savePage();download(new Blob([JSON.stringify({app:"StudyPDF",file:state.file?.name||"",exportedAt:new Date().toISOString(),pages:state.annotations},null,2)],{type:"application/json"}),(state.file?.name||"document.pdf").replace(/\.pdf$/i,"")+"-annotations.json")};
tool("select");
